<?php

namespace GhaenCollege\ScrumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BacklogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BacklogRepository extends EntityRepository
{
}
