<?php

namespace GhaenCollege\ScrumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EpicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpicRepository extends EntityRepository
{
}
